### ISSUE TITLE
[Proposal] Using Gymnasium instead of Gym

### ISSUE THREAD

**Issue by rageSpin** [Farama-Foundation/D4RL#191]
### Proposal 

Can we adopt **Gymnasium** instead of Gym? Both on package requirement and in _Readme.md_?

### Motivation

Gym will not maintained anymore.

> The team that has been maintaining Gym since 2021 has moved all future development to [Gymnasium](https://github.com/Farama-Foundation/Gymnasium), a drop in replacement for Gym (import gymnasium as gym), and this repo isn't planned to receive any future updates. Please consider switching over to Gymnasium as you're able to do so.

### Pitch

Substitute  `import gym`  with
```python 
import gymnasium as gym
```
in the following contexts:
1. Readme.md
2. Site documentation
3. Any code example
4. package **requirements** 

@justinjfu

**Comment by WillDudley** [comment]
Hi,

As mentioned in the Readme, D4RL is currently being decommissioned and transferred to Gymnasium-robotics and Minari. Therefore, it is not intended to update D4RL itself, but it is being kept around for legacy/reproducibility purposes. 

I hope this clears up any confusion. If you have any questions please let me know.

**Comment by rageSpin** [comment]
Everything clear, thanks :)
