### ISSUE TITLE
[Proposal] A lite version with minimal requirements to just download the datasets

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/D4RL#195]
### Proposal 

A lite version with minimal requirements to just download the datasets

### Motivation
For installing d4rl there are too much and to complicated dependencies which are hard to install in many systems and may cause version conflicts.

In many cases the users of d4rl just want to download a dataset. 

### Pitch

A no (or very mininal) dependency version of d4rl to just download the datasets

### Alternatives

This one until a mayor rework of d4rl that has many dependencies dropped and can be installed without conflicts

### Additional context

I have developed just this so how can we incorporate this lite version?

[https://github.com/jamartinh/d4rllite](https://github.com/jamartinh/d4rllite)

I prefer this to be incorporated into the main d4rl as an option in the install like:
 pip install d4rl[lite] 
or
 conda install dr4llite

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/d4rl/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Hi @jamartinh, this is already in the works but in a new project called, minari, https://github.com/farama-Foundation/minari
We are aiming for minari to replace d4rl as the de facto offline RL project with one of the reasons being minimal requirements / flexibility as you describe in this issue
