### ISSUE TITLE
[Question] why d4rl's state dims are different from gym's ? 

### ISSUE THREAD

**Issue by wydxry** [Farama-Foundation/D4RL#197]
for example, bullet-hopper-medium-v0's state dim is 15，and Hopper-v4's state dim is 11, so where can i find the meaning of your data,  and what difference above these? https://www.gymlibrary.dev/environments/mujoco/hopper/

**Comment by pseudo-rnd-thoughts** [comment]
Hi, the pybullet and mujoco implementations of the hooper environment are different implementations. You might need to look at the specification files for their differences

**Comment by wydxry** [comment]
So bullet and mujoco are different engine for same env, Thank you for your useful and timely answer！I will try mujoco imple...
