### ISSUE TITLE
[Bug Report] Official website URL expired and redirects to unrelated site

### ISSUE THREAD

**Issue by denkiwakame** [Farama-Foundation/D4RL#239]
The official website link (https://sites.google.com/view/d4rl/home) listed in the README appears to have expired and now redirects to an Indonesian job application site. This could confuse users seeking the dataset, potentially leading them to inadvertently apply for jobs on the redirected site.

Any plan to migrate the website to a more stable platform, such as GitHub Pages (e.g., GitHub.io), to ensure the site remains accessible and to prevent further misdirection? This would help maintain the reliability of the resource and avoid confusion for users.

Thank you for your attention to this matter!

**Comment by younik** [comment]
Hi, D4RL is deprecated, check the README

**Comment by denkiwakame** [comment]
Thank you for maintaining valuable resource on offline RL and for taking the time to update the README.
