### ISSUE TITLE
Antmaze datasets broken

### ISSUE THREAD

**Issue by Mr-Pepe** [Farama-Foundation/D4RL#77]
The difference in x/y values between current observations and next observations has some extremely high values that imply that the ant jumped across the whole maze in a single step. 

There is a number of such samples, making me wonder whether the dataset is generally broken.

Can you please give a comment on that?

Use this to reproduce:

```
env = gym.make('antmaze-medium-diverse-v0')
dataset = d4rl.qlearning_dataset(env)

(dataset['next_observations'] - dataset['observations'])[:, 0].max()
>> 21.227503

(dataset['next_observations'] - dataset['observations'])[:, 1].max()
>> 16.82595
```

**Comment by Mr-Pepe** [comment]
antmaze-umaze-diverse-v0 is also broken.

antmaze-umaze-v0 seems fine.

**Comment by Mr-Pepe** [comment]
It looks like the timeout flags are not in sync with the actual trajectory ends.

**Comment by Mr-Pepe** [comment]
@justinjfu Any plans on fixing this?

**Comment by justinjfu** [comment]
This issue is next on my queue now - I'll try to get this resolved in the next week or so.
