### ISSUE TITLE
Rendering of DAPG environments does not work

### ISSUE THREAD

**Issue by Mr-Pepe** [Farama-Foundation/D4RL#81]
`env.render()` does not show anything and does not throw an error.

**Comment by Mr-Pepe** [comment]
No, and I am glad that I don't have to work with d4rl anymore, although the quality might have improved since I used it in late 2020/early 2021.

**Comment by Yusufma03** [comment]
Hi, @WendongZh you'll have to use `env.mj_render()` instead of `env.render()` according to DAPG's [example](https://github.com/aravindr93/hand_dapg/blob/master/dapg/utils/visualize_demos.py#L35).

**Comment by liovn** [comment]
> Hi, @WendongZh you'll have to use `env.mj_render()` instead of `env.render()` according to DAPG's [example](https://github.com/aravindr93/hand_dapg/blob/master/dapg/utils/visualize_demos.py#L35).嗨，你必须使用 `env.mj_render()` 而不是 `env.render()` 根据 DAPG 的示例。

hi,I meet this problem in the maze2d `env.render()` does not show anything.  have any help? thank you
